### ISSUE TITLE
get_map_file関数内における画像のキャッシュファイルへの保存エラー

### ISSUE THREAD

**Issue by LBJ-code** [akchan/cycle_navi#1]
初めまして，このcycle_naviを卒業する研究室の教授にプレゼントしようと使わせていただいております．  

README中のUsageに従って作業をしていたのですが，Usage中の`python gen_route_dat.py sample_gpx/tokyo_sample_route.kml`実行中にエラーが発生しました．   
エラーの表記は以下の通りです．  

> Traceback (most recent call last):
>   File "gen_route_dat.py", line 435, in <module>
>     main(route_file_path)
>   File "gen_route_dat.py", line 426, in main
>     collect_map_tile(map_dir_path, map_tile_to_collect, verbose=verbose)
>   File "gen_route_dat.py", line 374, in collect_map_tile
>     jpg_path = get_map_tile(zoom, tile_x, tile_y, gsij_obj)
>   File "gen_route_dat.py", line 346, in get_map_tile
>     Image.open(fp, formats=("PNG",)).convert("RGB").save(cache_path)
>   File "C:\Users\user\anaconda3\envs\general\lib\site-packages\PIL\Image.py", line 2237, in save
>     fp = builtins.open(filename, "w+b")
> PermissionError: [Errno 13] Permission denied: 'gsij_map_tile_cache\\12/3632/1616.jpg'

おそらく，エラー該当コード付近の
```python
os.makedirs(cache_path, exist_ok=True)
```
の個所において変数`cache_path`に`gsij_map_tile_cache\\12/3632/1616.jpg`のように~.jpgまでふくむパスが含まれており，ディレクトリ名`gsij_map_tile_cache\\12/3632`下に`1616.jpg`という名前のディレクトリが作成されてしまうことが問題だと思います．  
そこで該当コードを
```python
os.makedirs(os.path.dirname(cache_path), exist_ok=True)
```
と変えることで正常に動作しました．ご確認ください．

環境は以下の通りです．  

[環境1]
- Windows10 Pro
- Python3.8

[環境2]
- Ubuntu 20.04
- Python3.8

**Comment by akchan** [comment]
LBJ-codeさん

詳細なバグ報告をありがとうございます。
手元でも同様のエラーが出ること、当該修正で改善することを確認できました。
同修正をコードにマージさせていただきました。

今回は気づくのに時間がかかってしまい申し訳ありませんでした。
またお気づきの点がございましたらご指摘いただけますと嬉しいです。

趣向を凝らしたプレゼントをされるとはとてもお世話になった先生なのですね。
プレゼントが良い時間を作ってくれますように！
